### ISSUE TITLE
tests: No reference for AWS_REGION when running payment-3p local tests

### ISSUE THREAD

**Issue by nascit** [aws-samples/aws-serverless-ecommerce-platform#100]
- AWS_REGION not set by default  

● processPayment without item

    ConfigError: Missing region in config

      51 |     const apiUrl = (await ssm.getParameter({
      52 |         Name: "/ecommerce/"+env+"/payment-3p/api/url"
    > 53 |     }).promise()).Parameter.Value;
         |        ^
      54 |     const tableName = (await ssm.getParameter({
      55 |         Name: "/ecommerce/"+env+"/payment-3p/table/name"
      56 |     }).promise()).Parameter.Value;

**Comment by nmoutschen** [comment]
Hey!

I pushed a [commit yesterday](https://github.com/aws-samples/aws-serverless-ecommerce-platform/commit/15a16da3f18c74de786c9183869c52ff18e7dbb5) that made some changes to the integration tests for the payment-3p service. Could you try and tell me if you still experience the same issue?

**Comment by nascit** [comment]
Tested again after pulling last commit. Seems fixed.

**Comment by nmoutschen** [comment]
OK, I'll close this one in the meantime. If you're experiencing the issue again, feel free to open a new issue.
