### ISSUE TITLE
make check-deps error

### ISSUE THREAD

**Issue by patrickwerz** [aws-samples/aws-serverless-ecommerce-platform#141]
Hi all,
I set up a cloud 9 env (ubuntu, because aws linux ami had problems with pyenv) and installed pyenv with brew. 

When running make all I get the following error:
```
[*] check-deps platform
make[3]: Entering directory '/home/ubuntu/environment/aws-serverless-ecommerce-platform/platform'

  error: unknown option `-r'
```

Do you have any ideas why? 

Best Patrick

**Comment by nmoutschen** [comment]
Hi Patrick! Thanks a lot for reaching out.

Looking at the [script for check-deps](https://github.com/aws-samples/aws-serverless-ecommerce-platform/blob/master/tools/check-deps), `-r` is used for both yq and jq.

Could you check if they are up to date and if any of them don't support the `-r` flag? By the way, this project uses the [python version of yq](https://pypi.org/project/yq/).

**Comment by patrickwerz** [comment]
yes, you are right yq==2.10.0 seems to not know the -r option. With the latest version it is working.
