### ISSUE TITLE
make ci-orders fails unknown command 

### ISSUE THREAD

**Issue by opsinghis** [aws-samples/aws-serverless-ecommerce-platform#146]
Executing the make service command fails with the below error

`$ make ci-orders
[*] lint orders
Error: unknown command "/Users/XXXXX/code/aws-serverless-ecommerce-platform/orders/metadata.yaml" for "yq"
Run 'yq --help' for usage.
************* Module main
src/get_order/main.py:25:32: E1136: Value 'Optional' is unsubscriptable (unsubscriptable-object)
src/on_events/main.py:131:0: C0304: Final newline missing (missing-final-newline)
src/on_events/main.py:28:55: E1136: Value 'Optional' is unsubscriptable (unsubscriptable-object)

------------------------------------------------------------------
Your code has been rated at 9.53/10 (previous run: 9.53/10, +0.00)

[*] build orders
Resolved to /Users/XXXXXX/code/aws-serverless-ecommerce-platform/orders/build/resources/openapi.yaml
Checksum match for function create_order. Skipping
Checksum match for function get_order. Skipping
Checksum match for function on_events. Skipping
Checksum match for function table_update. Skipping
[*] tests-unit orders
Error: unknown command "/Users/XXXXXX/code/aws-serverless-ecommerce-platform/orders/metadata.yaml" for "yq"
Run 'yq --help' for usage.
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov /Users/XXXXXX/code/aws-serverless-ecommerce-platform/orders/build --cov-config /Users/XXXXXX/code/aws-serverless-ecommerce-platform/shared/tests/unit/coveragerc
  inifile: None
  rootdir: /Users/XXXXXX/code/aws-serverless-ecommerce-platform

make[2]: *** [tests-unit] Error 4
make[1]: *** [tests-unit-orders] Error 2
make: *** [ci-orders] Error 2`

**Comment by nmoutschen** [comment]
Hi and thanks a lot for reaching out!

It seems that there might be 2 potential issues there: one with `yq`, and one with `pytest`. Could you send the output of `yq --version` and `pytest --version`?

They should give you something like this:

```
$ yq --version
yq 2.10.0
```

```
$ pytest --version
This is pytest version 5.4.3, imported from /home/USERNAME/.pyenv/versions/3.8.1/envs/ecommerce-platform/lib/python3.8/site-packages/pytest/__init__.py
setuptools registered plugins:
  requests-mock-1.7.0 at /home/USERNAME/.pyenv/versions/3.8.1/envs/ecommerce-platform/lib/python3.8/site-packages/requests_mock/contrib/_pytest_plugin.py
  pytest-cov-2.8.1 at /home/USERNAME/.pyenv/versions/3.8.1/envs/ecommerce-platform/lib/python3.8/site-packages/pytest_cov/plugin.py
```

Could you also send the output for `make validate-pyenv` and `make requirements`?

The first one should return something like this:

```
$ make validate-pyenv
make: Nothing to be done for 'validate-pyenv'.
```

**Comment by opsinghis** [comment]
Thanks a lot, it was the issue, I was missing the following. I have installed them now. its now executing the make ci-orders correctly.

pip3 install pytest-cov
pip3 install requests
pip3 install requests_mock

Regards
Om

**Comment by opsinghis** [comment]
Also when I run
$ make validate-pyenv
Makefile:133: *** Add 'pyenv init' to your shell to enable shims and autocompletion..  Stop.

$ make requirements
[*] Install Python requirements
make: pip: No such file or directory
make: *** [requirements] Error 1

I have python 3 installed. Also my pip3 command works fine. Some where I need to set the pip to pip3

**Comment by opsinghis** [comment]
The above problem was solved setting the following in the .bashrc on a Mac machine
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init init -I need to source file on the command prompt.

then running make validate
make: Nothing to be done for `validate'.

.make validate-pyenv
make: Nothing to be done for `validate-pyenv'.

I then ran the make requirements

$ make requirements
Traceback (most recent call last):
  File "tools/services", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "tools/services", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "tools/services", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "tools/services", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "tools/services", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "tools/services", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "tools/services", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "tools/services", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "tools/services", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "tools/services", line 9, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
[*] Install Python requirements
Collecting awscli==1.18.11 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/8b/13/d7a0fad834271c7ce29c2345d905ac23da4bbc533f53a8880ad58a1bff24/awscli-1.18.11-py2.py3-none-any.whl
Collecting aws-requests-auth==0.4.2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/a7/ba/e1601d0508b4150f8fe503f681079a7c9a17f7aa44e0d5cc42b9e3abdb8e/aws-requests-auth-0.4.2.tar.gz
Collecting cfn-lint==0.28.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/a4/7d/a8ebd78190370e2db3ea753bb0f9f497a29c55d243e49db3b3fff59bec96/cfn_lint-0.28.2-py3-none-any.whl
Collecting jsonschema==3.2.0 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/c5/8f/51e89ce52a085483359217bc72cdbf6e75ee595d5b1d4b5ade40c7e018b8/jsonschema-3.2.0-py2.py3-none-any.whl
Collecting locust==1.0.3 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/18/e5/c2c91a3bf6e7812d9454117f2616050454a7ecc016b452e223d5c52d7911/locust-1.0.3-py3-none-any.whl
Collecting pylint==2.4.4 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/e9/59/43fc36c5ee316bb9aeb7cf5329cdbdca89e5749c34d5602753827c0aa2dc/pylint-2.4.4-py3-none-any.whl
Collecting pytest==5.4.3 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/9f/f3/0a83558da436a081344aa6c8b85ea5b5f05071214106036ce341b7769b0b/pytest-5.4.3-py3-none-any.whl
Collecting pytest-cov==2.8.1 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/b9/54/3673ee8be482f81527678ac894276223b9814bb7262e4f730469bb7bf70e/pytest_cov-2.8.1-py2.py3-none-any.whl
Collecting PyYAML==5.3 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/3d/d9/ea9816aea31beeadccd03f1f8b625ecf8f645bd66744484d162d84803ce5/PyYAML-5.3.tar.gz
Collecting requests==2.23.0 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl
Collecting requests-mock==1.7.0 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/8c/f1/66c54a412543b29454102ae74b1454fce2d307b1c36e6bd2e9818394df88/requests_mock-1.7.0-py2.py3-none-any.whl
Collecting websockets==8.1 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/d8/e1/9897d72c461388834f4e0ecf5c4e91a31f157aaebdd7e8eb5dfb73481acc/websockets-8.1-cp38-cp38-macosx_10_9_x86_64.whl
Collecting yq==2.11.1 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/5f/1a/78c2b801ccef7cbfc536a5ebfd215349c2674ae2bc8ad9c77afeb41ac1bb/yq-2.11.1-py2.py3-none-any.whl
Collecting s3transfer<0.4.0,>=0.3.0 (from awscli==1.18.11->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/69/79/e6afb3d8b0b4e96cefbdc690f741d7dd24547ff1f94240c997a26fa908d3/s3transfer-0.3.3-py2.py3-none-any.whl
Collecting rsa<=3.5.0,>=3.1.2 (from awscli==1.18.11->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl
Collecting botocore==1.15.11 (from awscli==1.18.11->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/e5/e8/c2cb7845cab6d7694fc82f9cff8916f89b1233aa4d881c6cbeaac42b82b9/botocore-1.15.11-py2.py3-none-any.whl
Collecting docutils<0.16,>=0.10 (from awscli==1.18.11->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting colorama<0.4.4,>=0.2.5; python_version != "3.4" (from awscli==1.18.11->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/c9/dc/45cdef1b4d119eb96316b3117e6d5708a08029992b2fee2c143c7a0a5cc5/colorama-0.4.3-py2.py3-none-any.whl
Collecting jsonpatch; python_version != "3.4" (from cfn-lint==0.28.2->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/4f/d0/34b0f59ac08de9c1e07876cfecd80aec650600177b4bd445124c755499a7/jsonpatch-1.26-py2.py3-none-any.whl
Collecting six~=1.11 (from cfn-lint==0.28.2->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting aws-sam-translator>=1.19.1 (from cfn-lint==0.28.2->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/50/d6/2d5d5104f3052f27217388f43924704ebfe3350b97212d25155d219082ca/aws_sam_translator-1.29.0-py3-none-any.whl
Collecting pyrsistent>=0.14.0 (from jsonschema==3.2.0->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/4d/70/fd441df751ba8b620e03fd2d2d9ca902103119616f0f6cc42e6405035062/pyrsistent-0.17.3.tar.gz
Requirement already satisfied: setuptools in /Users/omsingh0/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from jsonschema==3.2.0->-r requirements.txt (line 4)) (41.2.0)
Collecting attrs>=17.4.0 (from jsonschema==3.2.0->-r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/c3/aa/cb45262569fcc047bf070b5de61813724d6726db83259222cd7b4c79821a/attrs-20.3.0-py2.py3-none-any.whl
Collecting ConfigArgParse>=1.0 (from locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/bb/79/3045743bb26ca2e44a1d317c37395462bfed82dbbd38e69a3280b63696ce/ConfigArgParse-1.2.3.tar.gz
Collecting gevent>=1.5.0 (from locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/1e/35/22fc11e3e82d66226a46a8cb63ac8fb5827b06325f93f59b77b4a6f32f18/gevent-20.9.0-cp38-cp38-macosx_10_15_x86_64.whl
Collecting psutil>=5.6.7 (from locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/33/e0/82d459af36bda999f82c7ea86c67610591cf5556168f48fd6509e5fa154d/psutil-5.7.3.tar.gz
Collecting Flask-BasicAuth>=0.2.0 (from locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/16/18/9726cac3c7cb9e5a1ac4523b3e508128136b37aadb3462c857a19318900e/Flask-BasicAuth-0.2.0.tar.gz
Collecting flask>=1.1.2 (from locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/f2/28/2a03252dfb9ebf377f40fba6a7841b47083260bf8bd8e737b0c6952df83f/Flask-1.1.2-py2.py3-none-any.whl
Collecting msgpack>=0.6.2 (from locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/aa/48/be5864c5c3604c07edf2eebaaacb1bb9afe600abc85295ffddb39f5ab529/msgpack-1.0.0-cp38-cp38-macosx_10_13_x86_64.whl
Collecting pyzmq>=16.0.2 (from locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/e7/46/5af276322d34e4fa069494696ce90738370726132093d3460e89f3093084/pyzmq-20.0.0-cp38-cp38-macosx_10_9_x86_64.whl
Collecting geventhttpclient>=1.4.2 (from locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/dd/43/e3af4ccf654c572ad9e55aa844f034b0021b501b9b14086de303dcd8a964/geventhttpclient-1.4.4-cp38-cp38-macosx_10_9_x86_64.whl
Collecting astroid<2.4,>=2.3.0 (from pylint==2.4.4->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/ad/ae/86734823047962e7b8c8529186a1ac4a7ca19aaf1aa0c7713c022ef593fd/astroid-2.3.3-py3-none-any.whl
Collecting isort<5,>=4.2.5 (from pylint==2.4.4->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl
Collecting mccabe<0.7,>=0.6 (from pylint==2.4.4->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting wcwidth (from pytest==5.4.3->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Collecting packaging (from pytest==5.4.3->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/46/19/c5ab91b1b05cfe63cccd5cfc971db9214c6dd6ced54e33c30d5af1d2bc43/packaging-20.4-py2.py3-none-any.whl
Collecting py>=1.5.0 (from pytest==5.4.3->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/68/0f/41a43535b52a81e4f29e420a151032d26f08b62206840c48d14b70e53376/py-1.9.0-py2.py3-none-any.whl
Collecting more-itertools>=4.0.0 (from pytest==5.4.3->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/66/58/63146600d8c35188f2c4de3f1e2fe77a54e9c9ac99ac3b652f09e042f637/more_itertools-8.6.0-py3-none-any.whl
Collecting pluggy<1.0,>=0.12 (from pytest==5.4.3->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/a0/28/85c7aa31b80d150b772fbe4a229487bc6644da9ccb7e427dd8cc60cb8a62/pluggy-0.13.1-py2.py3-none-any.whl
Collecting coverage>=4.4 (from pytest-cov==2.8.1->-r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/79/f4/0597fba8f0c13548091e73bfa1f00598df29a5b5651f59fb8e6c80105129/coverage-5.3-cp38-cp38-macosx_10_9_x86_64.whl
Collecting chardet<4,>=3.0.2 (from requests==2.23.0->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests==2.23.0->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/56/aa/4ef5aa67a9a62505db124a5cb5262332d1d4153462eb8fd89c9fa41e5d92/urllib3-1.25.11-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests==2.23.0->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests==2.23.0->-r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/c1/6f/3d85f0850962279a7e4c622695d7b3171e95ac65308a57d3b29738b27149/certifi-2020.11.8-py2.py3-none-any.whl
Collecting xmltodict>=0.11.0 (from yq==2.11.1->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Collecting argcomplete>=1.8.1 (from yq==2.11.1->-r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/d2/21/b0cecd5193b4d86818fe5b29b36f6bd5807ed9ab2d4a75681e1d3eaf7ba8/argcomplete-1.12.1-py2.py3-none-any.whl
Collecting pyasn1>=0.1.3 (from rsa<=3.5.0,>=3.1.2->awscli==1.18.11->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/62/1e/a94a8d635fa3ce4cfc7f506003548d0a2447ae76fd5ca53932970fe3053f/pyasn1-0.4.8-py2.py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1 (from botocore==1.15.11->awscli==1.18.11->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from botocore==1.15.11->awscli==1.18.11->-r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/07/cb/5f001272b6faeb23c1c9e0acc04d48eaaf5c862c17709d20e3469c6e0139/jmespath-0.10.0-py2.py3-none-any.whl
Collecting jsonpointer>=1.9 (from jsonpatch; python_version != "3.4"->cfn-lint==0.28.2->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/18/b0/a80d29577c08eea401659254dfaed87f1af45272899e1812d7e01b679bc5/jsonpointer-2.0-py2.py3-none-any.whl
Collecting boto3~=1.5 (from aws-sam-translator>=1.19.1->cfn-lint==0.28.2->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/6d/7e/3668fb3049a568dead633f8727810e04db95fda9269effdaf8abab56b8fd/boto3-1.16.18-py2.py3-none-any.whl
Collecting zope.event (from gevent>=1.5.0->locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/9e/85/b45408c64f3b888976f1d5b37eed8d746b8d5729a66a49ec846fda27d371/zope.event-4.5.0-py2.py3-none-any.whl
Collecting zope.interface (from gevent>=1.5.0->locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/92/98/ec429075ca578c2941e2871d9d79f894ef2ee7646f7ab9c690147e20964a/zope.interface-5.2.0-cp38-cp38-macosx_10_9_x86_64.whl
Collecting greenlet>=0.4.17; platform_python_implementation == "CPython" (from gevent>=1.5.0->locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/72/0c/fd07c7674ad6eded937194b84d8453425c36c6ef118536907b0185624d82/greenlet-0.4.17.tar.gz
Collecting Werkzeug>=0.15 (from flask>=1.1.2->locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/cc/94/5f7079a0e00bd6863ef8f1da638721e9da21e5bacee597595b318f71d62e/Werkzeug-1.0.1-py2.py3-none-any.whl
Collecting click>=5.1 (from flask>=1.1.2->locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting Jinja2>=2.10.1 (from flask>=1.1.2->locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
Collecting itsdangerous>=0.24 (from flask>=1.1.2->locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting wrapt==1.11.* (from astroid<2.4,>=2.3.0->pylint==2.4.4->-r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/23/84/323c2415280bc4fc880ac5050dddfb3c8062c2552b34c2e512eb4aa68f79/wrapt-1.11.2.tar.gz
Collecting lazy-object-proxy==1.4.* (from astroid<2.4,>=2.3.0->pylint==2.4.4->-r requirements.txt (line 6))
Collecting pyparsing>=2.0.2 (from packaging->pytest==5.4.3->-r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->flask>=1.1.2->locust==1.0.3->-r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/0c/12/37f68957526d1ec0883b521934b4e1b8ff3dd8e4fab858a5bf3e487bcee9/MarkupSafe-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl
ERROR: awscli 1.18.11 has requirement PyYAML<5.3,>=3.10, but you'll have pyyaml 5.3 which is incompatible.
ERROR: boto3 1.16.18 has requirement botocore<1.20.0,>=1.19.18, but you'll have botocore 1.15.11 which is incompatible.
Installing collected packages: PyYAML, six, python-dateutil, docutils, urllib3, jmespath, botocore, s3transfer, pyasn1, rsa, colorama, awscli, chardet, idna, certifi, requests, aws-requests-auth, pyrsistent, attrs, jsonschema, jsonpointer, jsonpatch, boto3, aws-sam-translator, cfn-lint, ConfigArgParse, zope.event, zope.interface, greenlet, gevent, psutil, Werkzeug, click, MarkupSafe, Jinja2, itsdangerous, flask, Flask-BasicAuth, msgpack, pyzmq, geventhttpclient, locust, wrapt, lazy-object-proxy, astroid, isort, mccabe, pylint, wcwidth, pyparsing, packaging, py, more-itertools, pluggy, pytest, coverage, pytest-cov, requests-mock, websockets, xmltodict, argcomplete, yq
  Running setup.py install for PyYAML ... done
  Running setup.py install for aws-requests-auth ... done
  Running setup.py install for pyrsistent ... done
  Running setup.py install for ConfigArgParse ... done
  Running setup.py install for greenlet ... done
  Running setup.py install for psutil ... done
  Running setup.py install for Flask-BasicAuth ... done
  Running setup.py install for wrapt ... done
Successfully installed ConfigArgParse-1.2.3 Flask-BasicAuth-0.2.0 Jinja2-2.11.2 MarkupSafe-1.1.1 PyYAML-5.3 Werkzeug-1.0.1 argcomplete-1.12.1 astroid-2.3.3 attrs-20.3.0 aws-requests-auth-0.4.2 aws-sam-translator-1.29.0 awscli-1.18.11 boto3-1.16.18 botocore-1.15.11 certifi-2020.11.8 cfn-lint-0.28.2 chardet-3.0.4 click-7.1.2 colorama-0.4.3 coverage-5.3 docutils-0.15.2 flask-1.1.2 gevent-20.9.0 geventhttpclient-1.4.4 greenlet-0.4.17 idna-2.10 isort-4.3.21 itsdangerous-1.1.0 jmespath-0.10.0 jsonpatch-1.26 jsonpointer-2.0 jsonschema-3.2.0 lazy-object-proxy-1.4.3 locust-1.0.3 mccabe-0.6.1 more-itertools-8.6.0 msgpack-1.0.0 packaging-20.4 pluggy-0.13.1 psutil-5.7.3 py-1.9.0 pyasn1-0.4.8 pylint-2.4.4 pyparsing-2.4.7 pyrsistent-0.17.3 pytest-5.4.3 pytest-cov-2.8.1 python-dateutil-2.8.1 pyzmq-20.0.0 requests-2.23.0 requests-mock-1.7.0 rsa-3.4.2 s3transfer-0.3.3 six-1.15.0 urllib3-1.25.11 wcwidth-0.2.5 websockets-8.1 wrapt-1.11.2 xmltodict-0.12.0 yq-2.11.1 zope.event-4.5.0 zope.interface-5.2.0
WARNING: You are using pip version 19.2.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


After this I ran make all and it executed well.

**Comment by nmoutschen** [comment]
Yep, that's expected: given the fact that many OSes, systems, etc. might have different installs (e.g. `pip` versus `pip3`), this project uses pyenv to ensure standardization. Closing as this is working for you now.
