### ISSUE TITLE
cfn-lint issue while make all-${Service}

### ISSUE THREAD

**Issue by srilives** [aws-samples/aws-serverless-ecommerce-platform#177]
Hi there,

Please help I am using cfn-lint v 1.9.7. when I am trying to make command, I get the following error -

Usage: cfn-lint [options] [command]

Options:
  -V, --version       output the version number
  -h, --help          output usage information

Commands:
  validate [options]
  docs

 No command provided!

**Comment by nmoutschen** [comment]
Awesome, thanks for the update! I'm closing the issue for now. 😄
