### ISSUE TITLE
AWSCloud9 Permissions Issue

### ISSUE THREAD

**Issue by narayandreamer** [aws-samples/aws-serverless-ecommerce-platform#191]
AWSCloud9 User created via IAM console gives numerous permission issues of not authorized.

Better to add a required permissions policy JSON for all resources to be used as template

**Comment by nmoutschen** [comment]
Hey @narayandreamer! What error are you seeing when you're using Cloud9?

**Comment by narayandreamer** [comment]
`An error occurred (UnauthorizedOperation) when calling the DescribeInstances operation: You are not authorized to perform this operation.`

Above is first of series. When i give above then others come, like that I have to give 1 by 1 as per error

**Comment by nmoutschen** [comment]
I'm unsure how this issue is related to this sample. As this is an entirely serverless application, it doesn't launch any EC2 instance, thus you don't need to perform any `DescribeInstances` call.

**Comment by narayandreamer** [comment]
Yes that i agree. But on dev environment as per your getting started guide if we use AWS Cloud9
![screenshot-github com-2021 12 14-18_07_09](https://user-images.githubusercontent.com/61919250/145999781-98b50953-4e17-44b2-969f-dbed23c05997.png)

**Comment by narayandreamer** [comment]
Ok got it.

According to you which is the best setup that will work for both dev (I use macOS) and prod. As i need to make it running first then change various services and add/remove

**Comment by nmoutschen** [comment]
Personally, I use my Mac directly to make changes to this project, then deploy into a dev AWS account (where I have full admin permissions). Then to deploy to production, I use a CI/CD pipeline that has the right permissions.

That said, while there is a sample pipeline in this project, it's still overly broad (see https://github.com/aws-samples/aws-serverless-ecommerce-platform/blob/main/pipeline/resources/service-pipeline-environment.yaml#L30), but scoped down to a single region.

**Comment by narayandreamer** [comment]
Ok I will give it a try from macOS then
