### ISSUE TITLE
payment-3p build depends on local typescript installation

### ISSUE THREAD

**Issue by cakepietoast** [aws-samples/aws-serverless-ecommerce-platform#82]
When running make all-payment-3p, the service fails to deploy properly as the typescript isn't transpiled. This is due to a missing typescript binary in my development environment. The build process shouldn't have dependencies on the local environment.

**Comment by nmoutschen** [comment]
Fixed by https://github.com/aws-samples/aws-serverless-ecommerce-platform/pull/83
